<Project Sdk="Microsoft.NET.Sdk">



	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>Nin_Online_Explorer</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>app.ico</ApplicationIcon>

		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishReadyToRun>true</PublishReadyToRun>
		<Nullable>disable</Nullable>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>



	<ItemGroup>

		<!-- asegura que el archivo .ico esté incluido en el proyecto -->

		<Content Include="app.ico" />

	</ItemGroup>



</Project>