<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>app.ico</ApplicationIcon>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishReadyToRun>true</PublishReadyToRun>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="background.png" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="app.ico" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="background.png" />
	</ItemGroup>
</Project>